management:
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      
      
springdoc:
  swagger-ui:
    path: /swagger-ui.html
